#!/bin/bash

docker ps -a | sed '1d' | docker ps --format "{{.ID}}\t{{.Image}}\t{{.Command}}\t{{.CreatedAt}}\t{{.Status}}\t{{.Names}}" | pick | cut -c1-12 | xargs -I % bash -c 'docker kill %; docker rm %'