#!/bin/bash

while read i; do
    exec 3</dev/tty
    echo -n "$i? (y/n) " >/dev/tty
    read -u 3 response
    case $response in
    	y) exec 3<&-; echo $i;;
	q) exec 3<&-; break;;
	*) exec 3<&-;;
    esac
done